import NavBar from './components/NavBar';
import './globals.css';
import { Inter, Montserrat } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
});
// const mont = Montserrat({
//   subsets: ['latin'],
//   variable: '--font-mont',
//   weight: '400',
// });

export const metadata = {
  title: 'Template - Next.js 13',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
